### ISSUE TITLE
Error in loading train_data

### ISSUE THREAD

**Issue by roadhouse23** [msultan/SML_CV#1]
Hello,
I would kindly ask you if you can help me in solving the following error when I execute 01-svm script

"IOError: Unable to load ./train_data/raw_features.pkl using the pickle or joblib protocol."

Thanks in advance
Gianvito

**Comment by msultan** [comment]
Two things to check:
1. Are you on python 3 ? The pickle protocol was broken between python 2 and 3 so this repo only works with python 3. 

2. Does the file raw_features.pkl actually exist in the train_data folder for you? Maybe it wasn't copied over properly?

**Comment by roadhouse23** [comment]
Thanks for your prompt reply.

Now I tried with python 3 and probably I solved the problem. However, now I
got the following:

"NameError: name 'get_ipython' is not defined"

Thanks again
Gianvito

Il giorno mer 8 ago 2018 alle ore 18:37 msultan <notifications@github.com>
ha scritto:

**Comment by msultan** [comment]
hmm, thats a strange one. What line are you getting this error? If its a plotting error, you can probably try to comment the plots and move ahead. Alternatively, I would recommend using anaconda's python3 package to get all the necessary basic python libraries.

**Comment by roadhouse23** [comment]
I solved by using anaconda's python3 package.Thank you. 

Gianvito

**Comment by msultan** [comment]
awesome! feel free to open another issue as the need arises.
