### ISSUE TITLE
Similarity between VAC metadynamics, TICA metadynamics, Supervised machine learning based CV selection and Harmonic Linear Discriminant Analysis

### ISSUE THREAD

**Issue by sbhakat** [msultan/SML_CV#4]
I have a simple question what is the difference between the above mentioned methods

For me VAC metadynamics is very similar to TICA metadynamics with some optimized scheme to give co-efficients to a previously selected CV set. Also VAC metadynamics somewhat resembles with supervised machine learning based CV selection where for each CV there is a kind of co-efficient (weight). 

LDA (https://arxiv.org/pdf/1808.07895.pdf )seems like a similar kind of concept of supervised machine learning based CV selection. Am I right?

That makes me wonder is kernel Harmonic Linear Discriminant Analysis the next paper? Because as per chronology TICA, kernel TICA based methods appered so why not LDA and kernel LDA based approach.

This was not a typical GITHUB issue but just a discussion. Hope people will share their views.

**Comment by msultan** [comment]
In our SML_CV paper, we already mention that kernel based methods are a good way to get non-linear functions. An alternative is to use deep learning based classifiers which is what we ended up using for the alanine model. The issue with kernels is that it becomes relatively slow for larger datasets, and requires the Nystorm approximation to work efficiently.  

It should be relatively easy to extend the LDA method with a non-linear kernel to make the LDA solution linear combinations of non-linear feature transforms.
